# Generated by Django 5.0.2 on 2024-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_visitante_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='morador_responsave',
            new_name='morador_responsavel',
        ),
    ]
